global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "elearn-services"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8080"  # api-gateway
          - "host.docker.internal:8085"  # user-service
          - "host.docker.internal:8082"  # course-service
          - "host.docker.internal:8086"  # review-service
          - "host.docker.internal:8084"  # purchasehistory-service
          - "host.docker.internal:8083"  # notification-service
